config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

    resources :companies do
      resources :employees, shallow: true #nuevo forma para aprender con el nesting
  end
  resources :employees, except: %i[index new create]
  resources :roles, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :departments, only: [:index, :new, :create, :edit, :update, :destroy]

    # Defines the root path route ("/")
    root "pages#home"
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_many :employees, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/department.rb
class Department < ApplicationRecord

  has_many :employees, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :role
  belongs_to :department
  belongs_to :company
  has_one_attached :avatar

  include PgSearch::Model

  pg_search_scope :search_by_name_role_and_department,
                  against: [:name],
                  associated_against: {
                    role: [:name],
                    department: [:name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  validates :name, presence: true
  validates :id_number, presence: true, uniqueness: true
end

#Las asociones has many crean 17 métodos nuevos .build y .employees
#Las asociones belongs to 7 métodos nuevos

app/models/role.rb
class Role < ApplicationRecord

  has_many :employees, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
  :recoverable, :rememberable, :validatable

  has_one :company




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Include it in the controllers (e.g. application_controller.rb)
include Pagy::Backend


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  before_action :set_company
  before_action :set_employee, only: [:show, :edit, :update, :destroy]


  def index
    @company = Company.find(params[:company_id])
    employees = if params[:search].present?
      @company.employees.includes(:role, :department).search_by_name_role_and_department(params[:search])
    else
      @company.employees.includes(:role, :department)
    end
    # @pagy, @employees = pagy(employees)

    respond_to do |format|
      format.html do
        @pagy, @employees = pagy(employees) #Solo paginar para html
      end
      format.xlsx  do #adentro van las instrucciones de la gema
        @employees = employees
        response.headers["Content-Disposition"] = "attachment; filename=empleados.xlsx"
      end
    end
  end

  def show
  end

  def new
    @employee = @company.employees.build  #creando una instancia vacia y al poner el build llena el numéro del papá pero a la vez agregando automáticamente el company_id
    @company = Company.find(params[:company_id])
  end

  def create
    @employee = @company.employees.build(employee_params)

    if @employee.save
      redirect_to company_employees_path(@company), notice: "Empleado creado con éxito."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      redirect_to employee_path(@employee), notice: "Empleado actualizado con éxito."
    else
      render :edit, status: :unprocessable_entity #422 error no se pudo procesar
    end
  end


  def destroy
    @employee.destroy
    redirect_to company_employees_path(@employee.company), notice: "Empleado eliminado con éxito.", status: :see_other #El status de destroy redirección permanente o 301
  end


  private

  def set_company
    @company = current_user.company # Se cambió de companies a company
    redirect_to root_path, alert: "Compañía no encontrada" if @company.nil?
  end
    #@company = current_user.companies.find_by(id: params[:company_id])
    #redirect_to root_path, alert: "Compañía no encontrada" if @company.nil?



  def set_employee
    @employee = Employee.find(params[:id])
    #@employee = @company.employees.find_by(id: params[:id]
    #redirect_to company_employees_path(@company), alert: "Empleado no encontrado" if @employee.nil?
  end


  def employee_params
    params.require(:employee).permit(:name, :birth_date, :id_number, :role_id, :department_id, :avatar)
  end
end


#turbo stream es codigo de Javascript disfrazado de Ruby

#alt z achicar texto ctrl + para agrandar

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/practica.rb
module Axlsx
  class Package
  end

end
Package.new #

app/helpers/application_helper.rb
module ApplicationHelper

  include Pagy::Frontend
  
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/_employee.html.erb
 <tr>
        <td><%= employee.name %></td>
        <td><%= ((Time.zone.now - employee.birth_date.to_time) / 1.year).floor %> años</td>
        <td><%= employee.id_number %></td>
        <td><%= employee.role.try(:name) %></td>
        <td><%= employee.department.try(:name) %></td>
        <td><% if employee.avatar.attached? %><%= cl_image_tag employee.avatar.key, width: 50, crop: :fill, class: "rounded-circle" %>
        <% else %>No tiene avatar<% end %></td>

        <td>
          <%= link_to employee_path(employee), class: "btn btn-success" do %>
          <i class="fa-solid fa-binoculars"></i>
          <% end %>
          <%= link_to edit_employee_path(employee), class: "btn btn-warning" do %>
          <i class="fa-sharp fa-solid fa-pen-to-square"></i>
          <% end %>
          <%= link_to employee_path(employee), data: { turbo_method: :delete, turbo_confirm: '¿Estás seguro de eliminar este empleado?' }, class: "btn btn-danger" do %>
          <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </td>
      </tr>

app/views/employees/_form.html.erb
<div class="container d-flex justify-content-center align-items-center vh-100"> <%# Esta instrucción es para conectar con un controlador de stimulus conecta el codigo de Javascript con el html el data-controller %>
  <div class="col-md-6 p-4 bg-white rounded shadow-lg">
    <h3 class="text-center mb-4"><strong>Información del empleado</strong></h3>
    <%= simple_form_for @employee, url: @employee.new_record? ? company_employees_path(@company) : employee_path(@employee) do |f| %>
      <div class="form-group">
        <%= f.input :name, label: raw("<strong>Nombre</strong>"), required: false, input_html: { class: "form-control" }, label_html: { class: "font-weight-bold" } %>
      </div>

      <div class="form-group">
        <label class="font-weight-bold"><strong>Fecha de Nacimiento</strong></label>
        <div class="d-flex gap-2">
          <%= f.input :birth_date, as: :string,
                      start_year: Date.today.year - 100,
                      end_year: Date.today.year,
                      order: [:day, :month, :year],
                      label: false,
                      input_html: {
                        class: "form-control d-inline w-auto",
                        data: {
                          controller:"datepicker"
                        }
                      } %>
                      <%# html5 es para el calendario en la vista para uso moderno. Cuando queramos definir un atributo html en un f. input debemos tener input_html:{} %>
        </div>
      </div>
  <%# El controlador de stimulus permite crear codigo de Javascript para usarlo en Ruby on rails,si yo quiero ver funcionando el codigo de Javascript tengo que conectarlo con html %>

      <div class="form-group">
        <%= f.input :id_number, label: raw("<strong>Cédula</strong>"), required: false, input_html: { class: "form-control" }, label_html: { class: "font-weight-bold" } %>
      </div>

       <div class="form-group">
        <%= f.association :department, label: raw("<strong>Departamento</strong>"), prompt: "Selecciona un departamento", input_html: { class: "form-control" }, label_html: { class: "font-weight-bold" } %>
      </div>

      <div class="form-group">
        <%= f.association :role, label: raw("<strong>Cargo</strong>"), prompt: "Seleccione un cargo", input_html: { class: "form-control" }, label_html: { class: "font-weight-bold" } %>
      </div>

      <div class="form-group">
        <%= f.input :avatar, as: :file, label: raw("<strong>Subir Avatar</strong>"), input_html: { class: "form-control" }, label_html: { class: "font-weight-bold" } %>
      </div>

      <div class="form-group mt-3 text-center">
        <%= f.submit @employee.new_record? ? "Crear nuevo empleado" : "Guardar cambios", class: "btn btn-outline-success mx-1" %>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/edit.html.erb
<%= render "form" %>

app/views/employees/index.html.erb
<h2 class="m-5 text-center">
  <strong>Lista de Empleados (<%= @company.employees.count %>)</strong>
</h2>

<div class="container">
  <div class="d-flex justify-content-between align-items-center m-3">
    <%= link_to new_company_employee_path(@company), class: "btn btn-success" do %>
      <i class="fa-solid fa-user-plus me-2"></i> Agregar Empleado
    <% end %>
    <%= link_to company_employees_path(@company, format: :xlsx), class: "btn btn-success" do %>
      <i class="fa-solid fa-file-excel me-2"></i> Exportar a Excel
    <% end %>
  </div>
  <div class="d-flex justify-content-end m-2">
    <%= form_tag company_employees_path(@company), method: :get, class: "form-inline" do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Buscar" %>
        <div class="input-group-append">
          <%= submit_tag "Buscar", class: "btn btn-secondary" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="table-responsive bg-white shadow rounded p-4 m-2">
    <div class="d-flex justify-content m-3">
      <%= raw pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    </div>
    <table class="table table-striped text-center mb-0">
      <thead class="border-bottom table-dark text-white">
        <tr>
          <th class="p-3">Nombre</th>
          <th class="p-3">Edad</th>
          <th class="p-3">Cédula</th>
          <th class="p-3">Cargo</th>
          <th class="p-3">Departamento</th>
          <th class="p-3">Avatar</th>
          <th class="p-3">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <%= render @employees %>
      </tbody>
    </table>

    <div class="d-flex justify-content-end m-3">
      <%= raw pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %> <%# El doble igual es lo que hace interpretar la etiqueta en HTML %>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<%= render "form" %>

app/views/employees/show.html.erb
<div class="container d-flex flex-column align-items-center justify-content-center vh-100">
  <h1 class="mb-4">Detalles del Empleado</h1>

  <% if @employee.avatar.attached? %>
    <div class="text-center mb-3">
      <%= image_tag @employee.avatar, alt: "Foto de #{@employee.name}", width: 180, class: "rounded-circle shadow border p-1" %>
    </div>
  <% end %>

  <table class="table table-hover w-50 text-center shadow-sm">
    <tr>
      <th>Nombre</th>
      <td><%= @employee.name %></td>
    </tr>
    <tr>
      <th>Fecha de Nacimiento</th>
      <td><%= @employee.birth_date %></td>
    </tr>
    <tr>
      <th>ID</th>
      <td><%= @employee.id_number %></td>
    </tr>
    <tr>
      <th>Rol</th>
      <td><%= @employee.role.name if @employee.role %></td>
    </tr>
    <tr>
      <th>Departamento</th>
      <td><%= @employee.department.name if @employee.department %></td>
    </tr>
    <tr>
      <th>Empresa</th>
      <td><%= @employee.company.name if @employee.company %></td>
    </tr>
  </table>

  <div class="mt-3">
    <%= link_to "Editar", edit_employee_path(@employee), class: "btn btn-outline-primary mx-1" %>
    <%= link_to "Eliminar", employee_path(@employee),
        data: { turbo_method: :delete, turbo_confirm: "¿Estás seguro que deseas eliminar este empleado?" },
        class: "btn btn-outline-danger mx-1" %>
    <%= link_to "Volver", company_employees_path(@employee.company), class: "btn btn-outline-secondary mx-1" %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-black shadow-lg">
  <div class="container-fluid">
    <% if user_signed_in? && current_user.company %>
      <span class="navbar-text ms-4 fs-1 fw-bold text-white">
        <%= current_user.company.name %>
      </span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? && current_user.company %>
          <li class="nav-item">
            <%= link_to 'Empleados', company_employees_path(current_user.company), class: 'nav-link fw-semibold text-white fs-5' %>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Cerrar sesión', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-link text-danger fw-semibold fs-5' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link fw-semibold text-dark fs-5' %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empleados</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

<%# Se ponen las lineas para servidor externo es mejor usar el importmap %>

app/views/pages/home.html.erb
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
    <h1><strong>¡Bienvenido a tu aplicación de Empleados!</strong></h1>
</div>